CONFIG_I2C=y
CONFIG_GPIO=y

# Enable Sensor subsystem and LIS3DH driver
CONFIG_SENSOR=y
CONFIG_LIS2DH=y

# Enable runtime interrupt handling via global thread
CONFIG_LIS2DH_TRIGGER_GLOBAL_THREAD=y

# Ensure printk can handle formatting and has enough stack space inside the thread
CONFIG_PRINTK=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BUILD_OUTPUT_UF2=y