CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_PM=y
CONFIG_POWEROFF=y

# Ensure printk can handle formatting and has enough stack space inside the thread
CONFIG_PRINTK=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BUILD_OUTPUT_UF2=y