CONFIG_GPIO=y
CONFIG_I2C=y

# Power management (needed for sys_poweroff)
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_POWEROFF=y

CONFIG_BUILD_OUTPUT_UF2=y

# No logging at all
CONFIG_LOG=y
CONFIG_PRINTK=y

# lpwr optimize
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y


