CONFIG_GPIO=y
CONFIG_I2C=y

# Power management (needed for sys_poweroff)
CONFIG_PM=y
CONFIG_POWEROFF=y

# Enable Sensor subsystem and LIS3DH driver
CONFIG_SENSOR=y

CONFIG_BUILD_OUTPUT_UF2=y

# No logging at all
CONFIG_LOG=n
CONFIG_PRINTK=n

# lpwr optimize
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_CONSOLE=n


