CONFIG_SERIAL=y
CONFIG_GPIO=y

# Enable Interrupt Driven UART (Required by GNSS driver subsystem)
CONFIG_UART_INTERRUPT_DRIVEN=y

# Enable Native Zephyr GNSS Subsystem & NMEA Generic Parser
CONFIG_GNSS=y
CONFIG_GNSS_NMEA_GENERIC=y

# Heap memory allocation for driver initializations and malloc calls
CONFIG_HEAP_MEM_POOL_SIZE=4096

# Enable UF2 Build Outputs
CONFIG_BUILD_OUTPUT_UF2=y

# ===================================================================
# ZEPHYR LOGGING SYSTEM CONFIGURATIONS
# ===================================================================
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y

# Set Global Log Levels (Default minimal level across the system)
CONFIG_LOG_DEFAULT_LEVEL=3