CONFIG_GPIO=y

# Power management (needed for sys_poweroff)
CONFIG_PM=y
CONFIG_POWEROFF=y

# No logging at all
CONFIG_LOG=n
CONFIG_PRINTK=n

# Optional: reduce idle overhead
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024

# lpwr optimize
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_CONSOLE=n