# # Journalisation générale
# CONFIG_LOG=y

# # Pile Réseau Fondamentale
# CONFIG_NETWORKING=y
# CONFIG_NET_IPV4=y
# CONFIG_NET_SOCKETS=y

# # Activation correcte d'ICMP (Ping) pour IPv4

# # Activation de la couche PPP native
# CONFIG_NET_L2_PPP=y
# CONFIG_MODEM_CMUX=n
# # Le framework modem moderne de Zephyr
# CONFIG_MODEM=y
# CONFIG_MODEM_CELLULAR=y
# CONFIG_MODEM_CELLULAR_APN="TM"
# CONFIG_BUILD_OUTPUT_UF2=y
# CONFIG_LOG_DEFAULT_LEVEL=2

# CONFIG_MODEM_LOG_LEVEL_DBG=y
# CONFIG_NET_PPP_LOG_LEVEL_DBG=y
# CONFIG_NET_L2_PPP_LOG_LEVEL_DBG=y
# CONFIG_NET_LOG=y
# CONFIG_NET_CORE_LOG_LEVEL_DBG=y
# CONFIG_NET_IF_LOG_LEVEL_DBG=y
# CONFIG_NET_MGMT_EVENT_LOG_LEVEL_DBG=y

# # Make sure you have enough log buffer
# CONFIG_LOG_BUFFER_SIZE=4096
# CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048

# CONFIG_USB_DEVICE_LOG_LEVEL_OFF=y
# CONFIG_UDC_DRIVER_LOG_LEVEL_OFF=y
# CONFIG_MPU_LOG_LEVEL_OFF=y

CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y

CONFIG_MODEM_CELLULAR=y

CONFIG_LOG=y

CONFIG_BUILD_OUTPUT_UF2=y
